/* Local review build. Public facts originate in content-data.js; no external submission. */
const data = window.JINLIYUAN_DATA;
const zh = new URLSearchParams(location.search).get("lang") !== "en";
const A = (file) => `assets/official/${file}`;
const route = () => location.hash.replace(/^#\/?/, "").replace(/\/$/, "") || "home";
const compactTitle = (value) => String(value || "").replace(/\s*[（(][^）)]*(?:一致性评价|20\s*mg|40\s*mg|80\s*mg)[^）)]*[）)]/gi, "").trim();
const labels = zh ? {
  home:"首页", about:"关于金立源", products:"产品中心", quality:"研发与制造", news:"企业动态", responsibility:"健康责任", disclosure:"信息公开", careers:"人才招聘", contact:"联系我们", search:"搜索", menu:"菜单", close:"关闭", all:"全部产品", formulation:"制剂产品", api:"原料药", intermediate:"医药中间体", other:"其他产品", productRecord:"查看产品资料", learn:"了解更多", back:"返回栏目首页", enquiry:"合作咨询"
} : {
  home:"Home", about:"About", products:"Products", quality:"Manufacturing", news:"Updates", responsibility:"Responsibility", disclosure:"Disclosures", careers:"Careers", contact:"Contact", search:"Search", menu:"Menu", close:"Close", all:"All products", formulation:"Finished medicines", api:"Active ingredients", intermediate:"Pharmaceutical intermediates", other:"Other products", productRecord:"View product record", learn:"Learn more", back:"Back to overview", enquiry:"Make an enquiry"
};
const productMedia = window.JINLIYUAN_PRODUCT_MEDIA || {};
const formulationIds = new Set([6,7,12,13,14,16,54,55]);
const typeOf = (p) => formulationIds.has(p.id) ? "formulation" : p.kind;
const PRODUCT_EN = {2:"Cilostazol",3:"Vitamin E Nicotinate",4:"Valsartan",5:"Irbesartan",6:"Telmisartan Tablets",7:"Ginseng Royal Jelly Capsules",12:"Pearl Powder Capsules",14:"Yupingfeng Oral Liquid",16:"Chuanbei Pipa Syrup",18:"Candesartan Cilexetil",19:"Atorvastatin Calcium",20:"Clopidogrel Hydrogen Sulfate",22:"Azilsartan",54:"Cilostazol Tablets",55:"Irbesartan Tablets"};
const productName = (p) => !zh && PRODUCT_EN[p.id] ? PRODUCT_EN[p.id] : compactTitle(p.title);
const sectionHead = (title, overline = "Zhejiang Kinglyuan Pharmaceutical", text = "") => `<section class="page-hero"><div class="wrap"><span class="eyebrow">${overline}</span><h1>${title}</h1>${text ? `<p>${text}</p>` : ""}</div></section>`;
const link = (to, text, cls = "") => `<a class="${cls}" href="#${to}">${text}</a>`;

const navGroups = [
  ["about", [["about/profile", zh?"企业简介":"Company profile"],["about/culture",zh?"企业文化":"Culture"],["about/honors",zh?"企业资质":"Qualifications"],["about/company",zh?"企业展示":"Our site"]]],
  ["products", [["products/formulation",labels.formulation],["products/api",labels.api],["products/intermediate",labels.intermediate],["products/other",labels.other],["products/adverse",zh?"不良反应报告":"Adverse event reporting"]]],
  ["quality", [["quality/production",zh?"生产体系":"Production"],["quality/management",zh?"质量管理":"Quality management"],["quality/platform",zh?"科研平台与产品研发":"Research & development"],["quality/collaboration",zh?"技术协作与成果":"Technical collaboration"]]],
  ["news", [["news/company",zh?"公司新闻":"Company news"],["news/industry",zh?"行业与技术":"Industry & technology"],["disclosure",zh?"信息公开":"Disclosures"]]],
  ["responsibility", [["responsibility/safety",zh?"职业健康与安全":"Health & safety"],["responsibility/environment",zh?"环境保护":"Environment"],["responsibility/community",zh?"公益与可持续":"Community & sustainability"]]],
  ["careers", [["careers/values",zh?"人才理念":"Working with us"],["careers/environment",zh?"工作环境":"Work environment"],["careers/openings",zh?"人才招聘":"Open roles"]]],
];
const navDescription = (key) => (zh ? {
  about:"企业基础、文化、资质与企业展示。", products:"制剂、原料药、中间体及完整产品资料。", quality:"生产、质量、研发与技术协作。", news:"公司动态、行业与技术记录。", responsibility:"职业健康、安全、环境与公益责任。", careers:"人才理念、工作环境与招聘联系。"
} : {
  about:"Company foundations, culture, qualifications and site imagery.", products:"Medicines, APIs, intermediates and product records.", quality:"Production, quality, research and collaboration.", news:"Company updates, industry and technical records.", responsibility:"Health, safety, environment and community practice.", careers:"People, working environment and recruitment contact."
})[key];
function navMarkup(){ return `${link("home",labels.home,"nav-home")}${navGroups.map(([key, children]) => `<div class="nav-group"><a class="nav-main" href="#${key}">${labels[key]}<span aria-hidden="true">↘</span></a><div class="mega"><div class="wrap mega-inner"><div class="mega-lead"><span class="eyebrow">${labels[key]}</span><strong>${labels[key]}</strong><p>${navDescription(key)}</p><a href="#${key}">${zh?"进入栏目首页":"View overview"} <i>↗</i></a></div><div class="mega-links">${children.map(([to,text], index)=>`<a href="#${to}"><small>${String(index+1).padStart(2,"0")}</small><b>${text}</b><i>↗</i></a>`).join("")}</div></div></div></div>`).join("")}${link("disclosure",labels.disclosure,"nav-plain")}${link("contact",labels.contact,"nav-plain")}<a class="nav-search" href="#search">${labels.search}</a>`; }
function shell(){
  document.documentElement.lang = zh ? "zh-CN" : "en";
  document.title = zh ? "浙江金立源药业" : "Kinglyuan Pharmaceutical";
  const alternate = `${location.pathname}${zh ? "?lang=en" : ""}${location.hash || "#home"}`;
  document.querySelector("#header").innerHTML = `<div class="site-header"><div class="wrap header-bar"><a class="brand" href="#home" aria-label="${zh?"金立源首页":"Kinglyuan home"}"><img src="${A("logo.png")}" alt="${zh?"金立源药业":"Kinglyuan Pharmaceutical"}"></a><button class="menu-button" type="button" aria-controls="primary-nav" aria-expanded="false"><span></span><span></span><b>${labels.menu}</b></button><nav id="primary-nav" class="primary-nav" aria-label="${zh?"主导航":"Primary navigation"}">${navMarkup()}</nav><a class="lang" href="${alternate}">${zh?"EN":"中文"}</a></div></div>`;
  document.querySelector("#footer").innerHTML = `<footer class="site-footer"><div class="wrap footer-layout"><div><img src="${A("logo.png")}" alt="${zh?"金立源药业":"Kinglyuan Pharmaceutical"}"><p>${zh?"浙江金立源药业有限公司":"Zhejiang Kinglyuan Pharmaceutical Co., LTD."}</p><p>${zh?"浙江省绍兴市上虞区杭州湾上虞经济技术开发区纬九路3号":"No. 3 Wei 9 Road, Hangzhou Bay Shangyu Economic & Technological Development Area, Shangyu, Shaoxing, Zhejiang"}</p></div><div class="footer-contact"><a href="tel:+8657582738388">+86-575-82738388</a><a href="mailto:kinglyuan@kinglyuan.com">kinglyuan@kinglyuan.com</a><p>© Zhejiang Kinglyuan Pharmaceutical Co., LTD.</p></div></div></footer>`;
  const button = document.querySelector(".menu-button"), nav = document.querySelector(".primary-nav");
  button.addEventListener("click", () => { const next = button.getAttribute("aria-expanded") !== "true"; button.setAttribute("aria-expanded",String(next)); nav.classList.toggle("is-open",next); button.querySelector("b").textContent = next ? labels.close : labels.menu; });
  nav.addEventListener("click", (event) => { if(event.target.closest("a")){ button.setAttribute("aria-expanded","false"); nav.classList.remove("is-open"); button.querySelector("b").textContent=labels.menu; } });
}
function productFeature(p){ const image=productMedia[p.id]; return `<a class="featured-product" href="#products/${p.id}">${image?`<img src="${A(image)}" alt="${productName(p)}">`:`<span class="product-graphic">${typeOf(p).toUpperCase()}</span>`}<div><small>${labels[typeOf(p)]}</small><strong>${productName(p)}</strong><span>${labels.productRecord} <i>↗</i></span></div></a>`; }
const disclosureMatcher = /环境|土壤|地下水|环保|竣工|调试|验收|公示|项目/;
const newsType = (n) => disclosureMatcher.test(n.title) ? (zh?"公开信息":"Disclosure") : ([1,3].includes(n.id) ? (zh?"行业与技术":"Industry & technology") : (zh?"公司新闻":"Company news"));
function newsRow(n){ return `<a class="update-row" href="#news/${n.id}"><time>${n.date}</time><span class="update-category">${newsType(n)}</span><strong>${n.title}</strong><i>↗</i></a>`; }
function home(){
 const featured=[55,6,54,7,12,14].map(id=>data.product.find(p=>p.id===id));
 const latest=[11,3,2].map(id=>data.news.find(n=>n.id===id));
 const heroTitle = zh ? "<span>专注制造，</span><span>守护健康。</span>" : "<span>Focused on manufacturing.</span><span>Committed to health.</span>";
 return `<section class="home-hero"><div class="hero-field" aria-hidden="true"></div><div class="wrap hero-copy"><span class="eyebrow">Zhejiang Kinglyuan Pharmaceutical</span><h1>${heroTitle}</h1><p>${zh?"以原料药、制剂、中间体及相关产品为基础，持续完善产品与制造体系。":"Across APIs, finished medicines, intermediates and related products, Kinglyuan brings its manufacturing and product information into one clear structure."}</p><div class="hero-actions"><a class="button" href="#products">${zh?"进入产品中心":"Explore products"}</a><a class="button button-light" href="#contact">${zh?"联系我们":"Contact us"}</a></div></div></section>
 <section class="section fact-section"><div class="wrap"><div class="split-heading"><div><span class="eyebrow">Why Kinglyuan</span><h2>${zh?"制造基础，面向长期健康。":"A manufacturing foundation for long-term health."}</h2></div><a href="#about/profile" class="quiet-link">${zh?"了解企业基础":"Company profile"} <i>↗</i></a></div><div class="fact-strip" data-counter-zone><article class="metric" data-value="20" data-suffix="+"><b>0</b><span>${zh?"年发展历程":"Years of development"}</span></article><article class="metric" data-value="560"><b>0</b><span>${zh?"名员工":"Employees"}</span></article><article class="metric metric-money" data-value="960" data-prefix="${zh?"¥":"RMB"}" data-suffix="M"><b>0</b><span>${zh?"资产规模":"Assets stated in profile"}</span></article><article class="metric" data-value="100" data-prefix="~"><b>0</b><span>${zh?"注册审批":"Registration approvals"}</span></article></div></div></section>
 <section class="section product-home"><div class="wrap"><div class="split-heading"><div><span class="eyebrow">Products</span><h2>${zh?"产品中心":"Product centre"}</h2><p>${zh?"从重点制剂到原料药与中间体，所有公开产品资料均可检索。":"From featured medicines to APIs and intermediates, public product information is structured for clear discovery."}</p></div><a href="#products" class="quiet-link">${zh?"查看全部 47 项产品":"Browse all 47 products"} <i>↗</i></a></div><div class="featured-products">${featured.map(productFeature).join("")}</div><div class="product-gates"><a href="#products/formulation"><span>01</span><b>${labels.formulation}</b><i>↗</i></a><a href="#products/api"><span>02</span><b>${zh?"原料药与相关产品":"APIs & related products"}</b><i>↗</i></a></div></div></section>
 <section class="manufacturing-home"><div class="wrap manufacture-layout"><div><span class="eyebrow">Manufacturing & quality</span><h2>${zh?"以制造为根基，<br>以质量为日常。":"Manufacturing at the core.<br>Quality in the everyday."}</h2><p>${zh?"生产、质量管理、科研平台、产品研发与技术协作，共同构成金立源的既有业务基础。":"Production, quality management, research platforms, product development and technical collaboration form Kinglyuan’s public business foundation."}</p><ol><li><span>01</span>${zh?"生产体系":"Production system"}</li><li><span>02</span>${zh?"质量管理":"Quality management"}</li><li><span>03</span>${zh?"科研与技术协作":"Research & collaboration"}</li></ol><a class="button button-light" href="#quality">${zh?"查看研发与制造":"Explore manufacturing"}</a></div><figure><img src="${A("home-project-4.jpg")}" alt="${zh?"金立源公开生产设备图片":"Kinglyuan publicly available production-equipment image"}"></figure></div></section>
 <section class="responsibility-home"><div class="wrap responsibility-layout"><figure><img src="${A("company-qy1.jpg")}" alt="${zh?"金立源公开企业环境图片":"Kinglyuan publicly available company-environment image"}"></figure><div><span class="eyebrow">Responsibility</span><h2>${zh?"长期建设，<br>从每一项责任开始。":"Long-term progress,<br>built through responsibility."}</h2><p>${zh?"职业健康与安全、环境保护、公益与可持续发展，均在网站中保留清晰入口与相关公开记录。":"Health and safety, environmental protection, community activity and sustainability retain clear routes and related public records."}</p><a href="#responsibility" class="quiet-link">${zh?"查看健康责任":"Explore responsibility"} <i>↗</i></a></div></div></section>
 <section class="section updates-home"><div class="wrap"><div class="split-heading"><div><span class="eyebrow">Company updates</span><h2>${zh?"企业动态":"Company updates"}</h2></div><a href="#news" class="quiet-link">${zh?"全部动态":"All updates"} <i>↗</i></a></div><div class="update-list">${latest.map(newsRow).join("")}</div></div></section>
 <section class="contact-band"><div class="wrap band-layout"><div><span class="eyebrow">Contact & cooperation</span><h2>${zh?"建立清晰的联系。":"Start with a clear conversation."}</h2></div><div><p>${zh?"产品、制造与合作咨询，欢迎通过电话、邮箱或在线表单联系。":"For product, manufacturing and cooperation enquiries, contact us by phone, email or the online enquiry form."}</p><a class="button button-light" href="#contact">${zh?"联系我们":"Contact Kinglyuan"}</a></div></div></section>`;
}

function about(sub){
 const page = {profile:zh?"企业简介":"Company profile",culture:zh?"企业文化":"Culture",honors:zh?"企业资质":"Qualifications",company:zh?"企业展示":"Our site"};
 if(!sub) return `${sectionHead(labels.about,"Zhejiang Kinglyuan Pharmaceutical",zh?"企业基础、文化、公开资质记录与企业展示。":"Company foundations, culture, public qualification records and company imagery.")}<section class="section about-overview"><div class="wrap"><div class="about-feature"><div><span class="eyebrow">Company profile</span><h2>${zh?"二十多年制造积累，<br>连接研发、生产与服务。":"More than two decades connecting research, manufacturing and service."}</h2><p>${zh?"从企业基础出发，了解金立源的规模、人才与长期建设。":"Start with the company foundation: scale, people and long-term development."}</p><a class="quiet-link" href="#about/profile">${zh?"阅读企业简介":"Read company profile"} <i>↗</i></a></div><figure><img src="${A("company-IMG_8706.jpg")}" alt="${zh?"金立源官网公开企业环境图片":"Officially published Kinglyuan company-environment image"}"></figure></div><div class="about-rails"><a href="#about/culture"><small>01</small><strong>${page.culture}</strong><p>${zh?"关爱生命、健康立源；协作、效率、进取与共享。":"Care for life, collaboration, efficiency, progress and shared value."}</p><i>↗</i></a><a href="#about/honors"><small>02</small><strong>${page.honors}</strong><p>${zh?"仅呈现可以核对的公开资质与荣誉记录。":"Only publicly traceable qualifications and recognition records."}</p><i>↗</i></a><a href="#about/company"><small>03</small><strong>${page.company}</strong><p>${zh?"保留旧官网公开的企业展示图像档案。":"An editorial archive of the legacy public company images."}</p><i>↗</i></a></div></div></section>`;
 if(sub === "profile") return profilePage(page.profile);
 if(sub === "culture") return culturePage(page.culture);
 if(sub === "honors") return honorsPage(page.honors);
 return galleryPage(page.company);
}
function profilePage(title){ return `${sectionHead(title,"About Kinglyuan",zh?"集研发、生产与服务于一体的综合性制药企业。":"An integrated pharmaceutical enterprise across research, manufacturing and service.")}<section class="section profile-story"><div class="wrap story-grid"><div><span class="eyebrow">Our foundation</span><h2>${zh?"在杭州湾畔，<br>建设稳定的制造基础。":"At Hangzhou Bay, building a steady manufacturing foundation."}</h2><p>${zh?"公司位于浙江省杭州湾畔。公开企业简介显示，金立源占地18万平方米，资产规模为9.6亿元人民币，拥有员工560人；经过二十多年的发展，形成研发、生产与服务一体化的企业基础。":"Located by Hangzhou Bay in Zhejiang, the public company profile states a 180,000-square-metre site, RMB 960 million in assets and a workforce of 560. Over more than two decades, Kinglyuan has developed an integrated research, manufacturing and service foundation."}</p></div><figure><img src="${A("company-IMG_8706.jpg")}" alt="${zh?"金立源公开企业环境图片":"Kinglyuan public company-environment image"}"></figure></div></section><section class="profile-metrics"><div class="wrap metric-grid"><div><b>20+</b><span>${zh?"年发展历程":"Years of development"}</span></div><div><b>560</b><span>${zh?"名员工":"Employees"}</span></div><div><b><small>${zh?"¥":"RMB"}</small>960<i>M</i></b><span>${zh?"资产规模":"Assets"}</span></div><div><b>${zh?"18万":"180,000"}</b><span>${zh?"平方米占地面积":"m² site area"}</span></div></div></section><section class="section people-section"><div class="wrap people-layout"><div><span class="eyebrow">People & expertise</span><h2>${zh?"持续建设，<br>来自长期的人才投入。":"Long-term development<br>depends on people."}</h2></div><div><p>${zh?"公开企业简介记载：具有高级职称的人员32人，中级及其他相关技术人员占职工总数的42%。":"The public company profile records 32 people with senior professional titles, while mid-level and other relevant technical personnel account for 42% of the workforce."}</p><div class="inline-facts"><span><b>32</b>${zh?"高级职称人员":"Senior-title personnel"}</span><span><b>42%</b>${zh?"中级及相关技术人员":"Mid-level & relevant technical personnel"}</span></div></div></div></section><section class="section profile-links"><div class="wrap"><span class="eyebrow">Explore further</span><div>${link("products",zh?"产品中心":"Products")}${link("quality",zh?"研发与制造":"Manufacturing")}${link("responsibility",zh?"健康责任":"Responsibility")}</div></div></section>`; }
function culturePage(title){ return `${sectionHead(title,"About Kinglyuan",zh?"关爱生命，健康立源。":"Care for life. Health through Kinglyuan.")}<section class="culture-lead"><div class="wrap"><span class="eyebrow">Our purpose</span><h2>${zh?"关爱生命，<br>让价值观进入日常。":"Care for life,<br>make values practical."}</h2><p>${zh?"以下内容整理自公司公开企业文化与人才理念，不将其改写为未经确认的新制度。":"The content below is structured from the company’s public culture and talent philosophy, without recasting it as unconfirmed new policy."}</p></div></section><section class="section culture-sequence"><div class="wrap"><article><span>01</span><div><h2>${zh?"企业宗旨":"Purpose"}</h2><p>${zh?"关爱生命，健康立源。":"Care for life. Health through Kinglyuan."}</p></div></article><article><span>02</span><div><h2>${zh?"经营理念":"Operating principles"}</h2><p>${zh?"团结协作、讲究效率、开拓进取、追求卓越。":"Collaboration, efficiency, progress and excellence."}</p></div></article><article><span>03</span><div><h2>${zh?"人才观":"People"}</h2><p>${zh?"人尽其才，物尽其用；给予信任、赋予责任、共享价值。":"Put people and potential to good use; build through trust, responsibility and shared value."}</p></div></article></div></section>`; }
function honorsPage(title){ const records = zh ? [["互联网药品信息服务资格备案","浙网药信备字(2026)00004号","官网页脚公开信息"],["绍兴市专利示范企业","公开科研成果页面记录","官网科研成果页"],["国家高新技术企业","公开科研成果页面记录","官网科研成果页"]] : [["Internet Pharmaceutical Information Service Filing","Zhe Internet Drug Information Filing No. (2026)00004","Official website footer"],["Shaoxing Patent Demonstration Enterprise","Recorded on the public research-results page","Official research-results page"],["National High-tech Enterprise","Recorded on the public research-results page","Official research-results page"]]; return `${sectionHead(title,"About Kinglyuan",zh?"公开资料可核对的资质与荣誉记录。":"Qualifications and recognition records traceable in public materials.")}<section class="section credential-page"><div class="wrap"><div class="credential-intro"><span class="eyebrow">Public records</span><h2>${zh?"事实先于装饰。":"Facts before decoration."}</h2><p>${zh?"旧官网的企业资质页没有可迁移的证书扫描件，因此本站不制作概念证书或暗示不存在的证书影像。企业提供原图后，本页可直接切换为可筛选、可放大的证书档案。":"The legacy qualifications page provides no certificate scans for migration. This site therefore does not fabricate certificate imagery. Once originals are provided, this page can become a filterable, zoomable certificate archive."}</p></div><div class="credential-list">${records.map((x,i)=>`<button type="button" class="credential" data-credential="${i}"><small>${String(i+1).padStart(2,"0")}</small><strong>${x[0]}</strong><span>${x[1]}</span><i>${zh?"查看来源":"View source"} ↗</i></button>`).join("")}</div></div></section><dialog class="source-dialog"><button class="dialog-close" type="button" aria-label="${zh?"关闭":"Close"}">×</button><span class="eyebrow">${zh?"公开来源信息":"Public source information"}</span><h2></h2><p class="source-meta"></p><p class="source-origin"></p><a class="quiet-link" href="https://www.kinglyuan.com/honors.html" target="_blank" rel="noreferrer">${zh?"查看官网公开页面":"View public source"} <i>↗</i></a></dialog>`; }
const galleryOrder=[1,2,4,5,6,7,9,11,13,14,3,8,10,12,15];
function galleryPage(title){ const tile=(id,index)=>`<button type="button" class="gallery-tile tile-${index+1}" data-gallery="${id}"><img src="${A(`gallery/qy${id}.jpg`)}" alt="${zh?`金立源公开企业展示图片 ${id}`:`Official Kinglyuan company-exhibition image ${id}`}" loading="lazy"><span>${zh?`企业展示 ${String(id).padStart(2,"0")}`:`Company exhibition ${String(id).padStart(2,"0")}`}</span></button>`; return `${sectionHead(title,"About Kinglyuan",zh?"来自旧官网企业展示栏目的完整公开图片档案。":"The complete public image archive from the legacy company-exhibition section.")}<section class="section gallery-page"><div class="wrap"><div class="gallery-note"><span class="eyebrow">Public image archive</span><p>${zh?"原图片没有提供拍摄说明；本站仅按公开顺序编号，不补写地点、设备或活动背景。首组精选11张，其余图片可展开查看。":"The original images have no captions. They remain numbered in public-source order, without invented locations, equipment names or event context. Eleven images are featured first; the remaining images are available on expansion."}</p></div><div class="editorial-gallery">${galleryOrder.slice(0,11).map(tile).join("")}</div><div class="gallery-rest" hidden>${galleryOrder.slice(11).map((id,i)=>tile(id,i+11)).join("")}</div><button class="gallery-expand" type="button" aria-expanded="false">${zh?"查看全部 15 张图片":"View all 15 images"}</button></div></section><dialog class="gallery-dialog"><button class="dialog-close" type="button" aria-label="${zh?"关闭":"Close"}">×</button><button class="gallery-prev" type="button" aria-label="${zh?"上一张":"Previous"}">←</button><figure><img src="" alt=""><figcaption></figcaption></figure><button class="gallery-next" type="button" aria-label="${zh?"下一张":"Next"}">→</button></dialog>`; }

function products(sub){
  if(sub === "adverse") return adversePage();
  const type = ["formulation","api","intermediate","other"].includes(sub) ? sub : "all";
  const title = type === "all" ? labels.products : labels[type];
  const intro = type === "all" ? (zh?"完整产品目录支持名称检索与分类筛选。重点制剂与原料药资料以不同的视觉方式呈现。":"The complete directory supports product-name search and category filters. Finished medicines and active ingredients use distinct visual treatment.") : (zh?`查看${labels[type]}的公开产品资料。`:`Browse public ${labels[type].toLowerCase()} records.`);
  const feature = type === "all" ? `<section class="featured-product-section"><div class="wrap"><div class="section-intro"><span class="eyebrow">Featured medicines</span><h2>${zh?"重点制剂":"Featured finished medicines"}</h2><p>${zh?"优先展示具有真实公开包装图的制剂产品。":"Finished medicines with authentic publicly available package imagery are prioritised here."}</p></div><div class="featured-products">${[55,6,54,7,12,14].map(id=>productFeature(data.product.find(p=>p.id===id))).join("")}</div></div></section>` : "";
  return `${sectionHead(title,"Products",intro)}${feature}<section class="section catalogue-section"><div class="wrap"><div class="catalogue-top"><div><span class="eyebrow">Product directory</span><h2>${type === "all" ? (zh?"全部产品资料":"All product records") : title}</h2></div><a href="#products" class="quiet-link">${labels.all} <i>↗</i></a></div><div class="catalogue-controls"><label><span>${zh?"搜索产品":"Search products"}</span><input id="product-search" type="search" placeholder="${zh?"输入产品名称、英文名或 CAS":"Product name, English name or CAS"}"></label><div id="product-filters" class="filter-pills">${["all","formulation","api","intermediate","other"].map(k=>`<button type="button" data-type="${k}" class="${k===type?"is-active":""}">${k==="all"?labels.all:labels[k]}</button>`).join("")}</div></div><p class="catalogue-count" id="product-count"></p><div class="directory-grid" id="product-results"></div></div></section><section class="product-contact"><div class="wrap"><span>${zh?"需要进一步产品资料？":"Need further product information?"}</span><a href="#contact/enquiry">${zh?"联系产品与合作团队":"Contact products & cooperation"} <i>↗</i></a></div></section>`;
}
function productCard(p){ const image=productMedia[p.id]; return `<a class="directory-card ${image?"has-photo":""}" href="#products/${p.id}">${image?`<img src="${A(image)}" alt="${productName(p)}" loading="lazy">`:`<div class="molecule-mark" aria-hidden="true"><span></span><span></span><span></span></div>`}<div><small>${labels[typeOf(p)]}</small><strong>${productName(p)}</strong><span>${labels.productRecord}<i>↗</i></span></div></a>`; }
function productDetail(id){ const p=data.product.find(item=>item.id===Number(id)); if(!p) return missing(); const image=productMedia[p.id]; return `${sectionHead(productName(p),labels.products,labels[typeOf(p)])}<section class="section product-detail"><div class="wrap detail-layout"><div class="detail-main"><span class="eyebrow">${labels[typeOf(p)]}</span><h2>${productName(p)}</h2>${image?`<figure><img src="${A(image)}" alt="${productName(p)}"></figure>`:""}<div class="public-notice">${zh?"本页仅整理审计到的公开产品记录；未添加适应症、疗效、规格、批准状态或采购状态等未经完整核验的信息。":"This page only organises audited public product records. It adds no unverified indications, efficacy claims, specifications, approval status or procurement status."}</div><p class="record-text">${p.auditedText}</p></div><aside><span>${zh?"产品咨询":"Product enquiry"}</span><p>${zh?"需要进一步沟通产品、资料或合作事宜，请联系金立源。":"For product, record or cooperation enquiries, contact Kinglyuan."}</p><a class="button" href="#contact/enquiry">${labels.enquiry}</a><a class="quiet-link" href="#products/${typeOf(p)}">${zh?"返回产品分类":"Back to category"} <i>↗</i></a></aside></div></section>`; }
function adversePage(){ return `${sectionHead(zh?"不良反应报告":"Adverse event reporting",labels.products,zh?"用于演示的简洁报告入口；当前不发送、不保存任何信息。":"A concise demonstration reporting route. It currently sends and stores no information.")}<section class="section form-page"><div class="wrap"><div class="form-note"><span class="eyebrow">Demo only</span><h2>${zh?"报告入口与隐私说明":"Reporting route and privacy note"}</h2><p>${zh?"如涉及不良反应或产品质量事件，可通过此入口演示报告流程。企业正式启用前需确认专用电话、邮箱、隐私告知和内部处置流程。":"This route demonstrates the reporting flow for adverse events or product quality concerns. A dedicated phone number, email, privacy notice and internal process require company confirmation before formal launch."}</p></div><form class="demo-form"><label>${zh?"称谓":"Name"}<input></label><label>${zh?"联系方式":"Contact details"}<input></label><label>${zh?"涉及产品":"Product"}<input></label><label>${zh?"事件描述":"Event description"}<textarea rows="5"></textarea></label><p>${zh?"演示阶段不发送、不保存。专用电话：XXX-XXXX-XXXX；专用邮箱：adr-xxx@kinglyuan.com（待企业确认）。":"Demo only: no data is sent or stored. Dedicated phone: XXX-XXXX-XXXX; email: adr-xxx@kinglyuan.com (pending company confirmation)."}</p><button type="button" disabled>${zh?"演示表单，暂不发送":"Demo form — not sent"}</button></form></div></section>`; }

const manufacturingPages = {
  production: zh ? {title:"生产体系", intro:"围绕产品制造建立清晰的生产组织与过程衔接。", lead:"让生产过程，保持可见的秩序。", copy:"生产体系页面聚焦公开的制造基础、过程衔接与相关企业展示资料；未公开的产能、车间等级和生产线参数不作补充。", image:"home-project-4.jpg", modules:[["制造范围","原料药、制剂、中间体及相关产品构成当前公开产品基础。"],["过程衔接","生产、质量与技术协作在同一制造体系中衔接。"],["相关资料","通过产品中心、质量管理与企业展示继续查看公开资料。"]]} : {title:"Production",intro:"A clear structure for manufacturing organisation and process connection.",lead:"Order made visible across production.",copy:"This page focuses on public manufacturing foundations, process connection and related company imagery. It adds no unverified capacity, cleanroom class or production-line parameters.",image:"home-project-4.jpg",modules:[["Manufacturing scope","APIs, finished medicines, intermediates and related products form the current public product base."],["Process connection","Production, quality and technical collaboration are connected within one manufacturing system."],["Related records","Continue to products, quality management and company imagery for public records."]]},
  management: zh ? {title:"质量管理",intro:"以过程、记录和沟通连接质量管理。",lead:"质量不是口号，<br>而是过程中的日常判断。",copy:"在现有公开资料边界内，本站呈现质量管理与生产、产品资料之间的关系；具体体系标准和放行参数等待企业确认后补充。",image:"home-project-3.jpg",modules:[["原辅料与过程","关注从原辅料到过程控制的质量衔接。"],["检测与记录","质量相关检测、记录和资料入口需以企业确认内容为准。"],["放行与沟通","产品资料、质量沟通与不良反应报告入口保持清晰分流。"]]} : {title:"Quality management",intro:"Quality management connected through process, records and communication.",lead:"Quality is not a slogan.<br>It is daily judgement in process.",copy:"Within the public-record boundary, this page shows the relationship between quality management, production and product records. Specific standards and release parameters await company confirmation.",image:"home-project-3.jpg",modules:[["Materials and process","Quality connection from inputs to process control."],["Testing and records","Testing and record details remain subject to company-confirmed information."],["Release and communication","Product information, quality enquiries and adverse-event reporting retain distinct routes."]]},
  platform: zh ? {title:"科研平台与产品研发",intro:"将研发、产品资料与制造基础放在同一条清晰路径中。",lead:"从产品问题出发，<br>连接研发与制造。",copy:"科研平台与产品研发来自原官网既有栏目。当前以产品导向和公开资料为主线，不虚构未公开的研发管线、设施或成果。",image:"home-project-3.jpg",modules:[["科研平台","保留原官网科研平台入口与相关公开资料。"],["产品研发","围绕产品资料组织研发信息与后续沟通。"],["公开成果","可核对的专利与科研相关记录进入企业资质和动态体系。"]]} : {title:"Research & product development",intro:"A clear path connecting research, product records and manufacturing foundations.",lead:"Start with product questions,<br>connect research and manufacturing.",copy:"Research platform and product development are retained from legacy public sections. The page follows product-led public records and does not fabricate pipeline, facility or outcome claims.",image:"home-project-3.jpg",modules:[["Research platform","The legacy platform route and relevant public records are retained."],["Product development","Product information organises research-related material and follow-up discussion."],["Public outcomes","Traceable patent and research records sit within qualifications and updates."]]},
  collaboration: zh ? {title:"技术协作与科研成果",intro:"为技术协作保留独立入口与明确联系路径。",lead:"让技术对话，<br>从清晰资料开始。",copy:"技术协作不与科研平台混成同一页。有关合作方向、成果和联系信息按公开材料组织，具体合作范围由企业后续确认。",image:"company-qy2.jpg",modules:[["技术协作","保留原官网技术协作栏目作为独立信息入口。"],["科研成果","公开的专利示范、高新技术企业等记录可在资质页核对。"],["合作联系","产品、研发与制造相关咨询可进入联系页面。"]]} : {title:"Technical collaboration",intro:"A distinct route for technical collaboration and research records.",lead:"Start technical dialogue<br>with clear records.",copy:"Technical collaboration is not collapsed into the research-platform page. Directions, records and contact routes are organised from public materials; specific collaboration scope remains for company confirmation.",image:"company-qy2.jpg",modules:[["Technical collaboration","The legacy technical-collaboration section remains a distinct route."],["Research records","Public patent-demonstration and high-tech-enterprise records can be checked in qualifications."],["Contact","Product, research and manufacturing enquiries can enter the contact page."]]}
};
function quality(sub){ const pageKey = sub === "research" || sub === "development" || sub === "outcomes" ? "platform" : (sub || ""); if(!pageKey) return qualityLanding(); const item=manufacturingPages[pageKey] || manufacturingPages.production; return `${sectionHead(item.title,"Manufacturing & quality",item.intro)}<section class="section manufacturing-detail ${pageKey}"><div class="wrap"><div class="manufacture-essay"><div><span class="eyebrow">${pageKey === "management" ? "Quality management" : pageKey === "production" ? "Production system" : pageKey === "platform" ? "Research & development" : "Technical collaboration"}</span><h2>${item.lead}</h2><p>${item.copy}</p></div><figure><img src="${A(item.image)}" alt="${item.title}"></figure></div><div class="process-map">${item.modules.map((m,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h3>${m[0]}</h3><p>${m[1]}</p></article>`).join("")}</div><div class="page-tail"><a href="#contact/enquiry">${zh?"联系相关团队":"Contact the relevant team"} <i>↗</i></a><a href="#quality">${labels.back} <i>↗</i></a></div></div></section>`; }
function qualityLanding(){ return `${sectionHead(labels.quality,"Manufacturing & quality",zh?"生产、质量、科研与技术协作，形成彼此关联但各自清晰的内容体系。":"Production, quality, research and collaboration form connected but distinct content systems.")}<section class="quality-overview"><div class="wrap"><figure><img src="${A("home-project-4.jpg")}" alt="${zh?"金立源公开制造设备图片":"Kinglyuan public manufacturing-equipment image"}"></figure><div><span class="eyebrow">Manufacturing foundation</span><h2>${zh?"让制造能力，<br>回到真实资料。":"Bring manufacturing back<br>to real records."}</h2><p>${zh?"从生产体系、质量管理、科研平台到技术协作，分别进入对应页面查看公开内容。":"Enter distinct pages for production, quality management, research platform and technical collaboration."}</p></div></div><div class="wrap quality-route-grid">${[["production",zh?"生产体系":"Production"],["management",zh?"质量管理":"Quality management"],["platform",zh?"科研平台与产品研发":"Research & development"],["collaboration",zh?"技术协作与科研成果":"Technical collaboration"]].map(([to,name],i)=>`<a href="#quality/${to}"><small>${String(i+1).padStart(2,"0")}</small><strong>${name}</strong><i>↗</i></a>`).join("")}</div></section>`; }

function news(sub){ const all=data.news, visible = sub === "company" ? all.filter(n=>newsType(n) === (zh?"公司新闻":"Company news")) : sub === "industry" ? all.filter(n=>newsType(n) === (zh?"行业与技术":"Industry & technology")) : all; const title=sub === "company" ? (zh?"公司新闻":"Company news") : sub === "industry" ? (zh?"行业与技术":"Industry & technology") : labels.news; return `${sectionHead(title,"Company updates",zh?"完整归档原官网公开的新闻、行业技术记录及相关动态。":"A complete archive of public company news, industry and technology records from the legacy site.")}<section class="section news-page"><div class="wrap"><div class="news-navigation"><a class="${!sub?"is-active":""}" href="#news">${zh?"全部动态":"All updates"}<b>${all.length}</b></a><a class="${sub==="company"?"is-active":""}" href="#news/company">${zh?"公司新闻":"Company news"}</a><a class="${sub==="industry"?"is-active":""}" href="#news/industry">${zh?"行业与技术":"Industry & technology"}</a><a href="#disclosure">${zh?"信息公开":"Disclosures"}</a></div><div class="news-archive">${visible.map(n=>`<a href="#news/${n.id}"><time>${n.date}</time><span>${newsType(n)}</span><div><strong>${n.title}</strong><p>${n.auditedText.replace(/\s+/g," ").slice(0,122)}…</p></div><i>↗</i></a>`).join("")}</div></div></section>`; }
function newsDetail(id){ const n=data.news.find(item=>item.id===Number(id)); if(!n) return missing(); return `${sectionHead(n.title,"Company updates",`${n.date} · ${newsType(n)}`)}<section class="section record-page"><div class="wrap"><article><span class="eyebrow">${newsType(n)}</span><p>${n.auditedText}</p><a class="quiet-link" href="${n.legacyUrl}" target="_blank" rel="noreferrer">${zh?"查看原公开记录":"View public source"} <i>↗</i></a></article><aside><span>${zh?"归档信息":"Archive"}</span><p>${n.date}</p><p>${newsType(n)}</p><a href="#news">${zh?"返回全部动态":"Back to updates"} <i>↗</i></a></aside></div></section>`; }
function disclosure(){ const records=[...data.news.filter(n=>disclosureMatcher.test(n.title)).map(n=>({title:n.title,date:n.date,url:n.legacyUrl,status:zh?"公开记录":"Public record"})),...data.pdfs.map((p,i)=>({title:p.title || (zh?`公开附件记录 ${i+1}`:`Public attachment record ${i+1}`),date:"",url:p.url,status:p.status}))]; return `${sectionHead(labels.disclosure,"Public information",zh?"环境、项目、监测与验收等公开信息独立归档；原文件无法取得时明确保留待取回状态。":"Environmental, project, monitoring and acceptance information is archived separately; unavailable original files retain an explicit pending-retrieval status.")}<section class="section disclosure-page"><div class="wrap"><div class="disclosure-intro"><span class="eyebrow">Archive</span><h2>${zh?"公开资料，清晰归档。":"Public records, clearly archived."}</h2><p>${zh?"每条记录先进入详情或原公开页面；本站不把无法取得的文件伪造成可下载附件。":"Each record leads to its detail or public source; unavailable files are not presented as downloadable attachments."}</p></div><div class="disclosure-list">${records.map((x,i)=>`<article><small>${String(i+1).padStart(2,"0")}</small><div><span>${x.status}</span><h3>${x.title}</h3>${x.date?`<time>${x.date}</time>`:""}</div>${x.url?`<a href="${x.url}" target="_blank" rel="noreferrer">${zh?"查看记录":"View record"} <i>↗</i></a>`:`<em>${zh?"原文件待取回":"Source file pending retrieval"}</em>`}</article>`).join("")}</div></div></section>`; }

const responsibilityContent = {
 safety: zh ? {title:"职业健康与安全",lead:"将职业健康与安全，放进日常管理。",copy:"职业健康与安全生产来自原官网既有社会责任栏目。本页保留清晰的责任入口、联系路径与后续企业确认空间，不补充未公开制度或安全指标。",image:"home-project-2.jpg",items:[["职业健康","保持职业健康相关信息与责任入口清晰可见。"],["安全生产","安全生产作为长期运营的重要组成保留独立信息层级。"],["相关联系","如有质量或不良反应事项，可使用专用报告入口。"]]} : {title:"Occupational health & safety",lead:"Put health and safety into daily management.",copy:"Occupational health and production safety are retained from the legacy responsibility section. This page provides clear routes, contact paths and room for company-confirmed additions without inventing policy or safety metrics.",image:"home-project-2.jpg",items:[["Occupational health","Keep health-related information and routes visible."],["Production safety","Retain production safety as an independent aspect of long-term operation."],["Related contact","Use the dedicated reporting route for quality or adverse-event matters."]]},
 environment: zh ? {title:"环境保护",lead:"把环境责任，<br>放进可查阅的公开记录。",copy:"环境保护与项目、监测及验收信息相互关联。公开文件和项目记录均进入信息公开栏目，避免与企业动态混杂。",image:"company-qy3.jpg",items:[["项目与公示","项目和环境相关公示进入独立归档。"],["监测与验收","监测、调试和验收记录保持原始日期与来源路径。"],["资料入口","进入信息公开查看所有已整理的公开资料。"]]} : {title:"Environment",lead:"Put environmental responsibility<br>into accessible public records.",copy:"Environmental protection is connected to project, monitoring and acceptance information. Public files and project records enter the disclosure archive instead of being mixed into company updates.",image:"company-qy3.jpg",items:[["Projects and notices","Project and environmental notices enter a distinct archive."],["Monitoring and acceptance","Monitoring, commissioning and acceptance records retain dates and source paths."],["Records","Use disclosures to view the organised public archive."]]},
 community: zh ? {title:"公益与可持续",lead:"以长期责任，<br>连接企业与公共价值。",copy:"公益慈善与可持续发展为原官网既有栏目。当前公开材料较少，因此页面保持克制，不以虚构故事或概念图片替代真实记录。",image:"company-qy1.jpg",items:[["公益慈善","保留原官网公益慈善栏目作为独立入口。"],["可持续发展","将长期责任与企业发展放在同一叙事中。"],["持续完善","后续可在企业提供真实活动和资料后扩展本页。"]]} : {title:"Community & sustainability",lead:"Connect company and public value<br>through long-term responsibility.",copy:"Community activity and sustainability are retained from legacy sections. Current public material is limited, so the page stays restrained and does not substitute fictional stories or conceptual imagery for real records.",image:"company-qy1.jpg",items:[["Community","Retain the legacy community route as a distinct entry."],["Sustainability","Connect long-term responsibility and company development in one narrative."],["Continued development","The page can expand once the company provides real activity records and materials."]]}
};
function responsibility(sub){ if(!sub) return responsibilityLanding(); const item=responsibilityContent[sub] || responsibilityContent.safety; return `${sectionHead(item.title,"Responsibility",item.copy)}<section class="section responsibility-detail ${sub}"><div class="wrap"><div class="responsibility-essay"><figure><img src="${A(item.image)}" alt="${item.title}"></figure><div><span class="eyebrow">Responsibility</span><h2>${item.lead}</h2><p>${item.copy}</p></div></div><div class="responsibility-steps">${item.items.map((x,i)=>`<article><span>${String(i+1).padStart(2,"0")}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</div><div class="page-tail"><a href="#${sub === "environment" ? "disclosure" : "contact"}">${sub === "environment" ? labels.disclosure : labels.contact} <i>↗</i></a><a href="#responsibility">${labels.back} <i>↗</i></a></div></div></section>`; }
function responsibilityLanding(){ return `${sectionHead(labels.responsibility,"Responsibility",zh?"职业健康与安全、环境保护、公益与可持续发展，保留为三个清晰而独立的责任入口。":"Occupational health and safety, environment, community and sustainability remain as three clear, independent responsibility routes.")}<section class="responsibility-landing"><div class="wrap"><div><span class="eyebrow">Long-term responsibility</span><h2>${zh?"责任不只是信息，<br>更是长期建设。":"Responsibility is not only information.<br>It is long-term work."}</h2></div><div class="responsibility-links">${[["safety",zh?"职业健康与安全":"Health & safety"],["environment",zh?"环境保护":"Environment"],["community",zh?"公益与可持续":"Community & sustainability"]].map(([to,name],i)=>`<a href="#responsibility/${to}"><small>${String(i+1).padStart(2,"0")}</small><span>${name}</span><i>↗</i></a>`).join("")}</div></div></section>`; }

function careers(sub){ if(sub === "openings") return openingsPage(); if(sub === "environment") return careersEnvironment(); return careersValues(); }
function careersValues(){ return `${sectionHead(labels.careers,"Careers",zh?"给予信任、赋予责任、共享价值。":"Trust, responsibility and shared value.")}<section class="section career-page"><div class="wrap career-layout"><div><span class="eyebrow">Working with us</span><h2>${zh?"人尽其才，<br>物尽其用。":"People and potential,<br>put to good use."}</h2></div><div><p>${zh?"我们致力于企业和人才共同发展的战略，建立能够充分展示能力的平台；给予信任、赋予责任、共享价值。":"Kinglyuan pursues shared development between the company and its people, building a platform for capability, trust, responsibility and shared value."}</p><a class="quiet-link" href="#careers/openings">${zh?"查看人才招聘":"View open roles"} <i>↗</i></a></div></div></section><section class="career-routes"><div class="wrap"><a href="#careers/environment"><span>01</span><strong>${zh?"工作环境":"Work environment"}</strong><i>↗</i></a><a href="#careers/openings"><span>02</span><strong>${zh?"人才招聘":"Open roles"}</strong><i>↗</i></a></div></section>`; }
function careersEnvironment(){ return `${sectionHead(zh?"工作环境":"Work environment","Careers",zh?"在真实业务与长期建设中积累专业能力。":"Build professional capability through real work and long-term development.")}<section class="section work-environment"><div class="wrap"><figure><img src="${A("gallery/qy11.jpg")}" alt="${zh?"金立源公开企业展示图片":"Kinglyuan public company image"}"></figure><div><span class="eyebrow">Working at Kinglyuan</span><h2>${zh?"以实际工作，<br>积累专业能力。":"Build capability<br>through real work."}</h2><p>${zh?"原官网公开人才理念强调，工作不只是一份工作；员工可以拥抱梦想、实现自我并为社会作出贡献。":"The public talent philosophy says work is more than a job: people can pursue ambitions, realise their potential and contribute to society."}</p></div></div></section>`; }
function openingsPage(){ return `${sectionHead(zh?"人才招聘":"Open roles","Careers",zh?"招聘信息以企业当前正式发布为准；本地样站保留清晰联系入口。":"Current positions remain subject to formal company publication; this local review build retains a clear contact route.")}<section class="section openings-page"><div class="wrap"><div class="openings-lead"><span class="eyebrow">Recruitment contact</span><h2>${zh?"与金立源一起，<br>在长期建设中成长。":"Grow with Kinglyuan<br>through long-term work."}</h2><p>${zh?"当前本地资料未包含可完整核验的具体岗位、人数和薪资字段，因此不编造职位清单。正式发布前可在此直接展开企业确认的岗位信息。":"Current local material does not contain fully verifiable role, headcount and compensation fields, so no job list is invented. Company-confirmed roles can be expanded directly here before formal publication."}</p></div><div class="recruitment-contact"><span>${zh?"招聘联系":"Recruitment contact"}</span><a href="tel:+8657582738388">+86-575-82738388</a><a href="mailto:kinglyuan@kinglyuan.com">kinglyuan@kinglyuan.com</a></div></div></section>`; }
function contact(sub){ if(sub === "enquiry") return enquiryPage(); return `${sectionHead(labels.contact,"Contact & cooperation",zh?"产品、制造、合作、人才与质量相关事项均可从此进入。":"Products, manufacturing, cooperation, careers and quality-related matters all have a clear route from here.")}<section class="section contact-page"><div class="wrap contact-layout"><div><span class="eyebrow">Kinglyuan Pharmaceutical</span><h2>${zh?"建立清晰的联系。":"Start with a clear conversation."}</h2><p>${zh?"对于产品、制造与合作信息，欢迎直接联系金立源。普通联系表单与不良反应报告分开处理。":"For product, manufacturing and cooperation information, contact Kinglyuan directly. General enquiries and adverse-event reporting are kept separate."}</p><a class="button" href="#contact/enquiry">${labels.enquiry}</a></div><dl><div><dt>${zh?"电话":"Telephone"}</dt><dd><a href="tel:+8657582738388">+86-575-82738388</a></dd></div><div><dt>${zh?"邮箱":"Email"}</dt><dd><a href="mailto:kinglyuan@kinglyuan.com">kinglyuan@kinglyuan.com</a></dd></div><div><dt>${zh?"传真":"Fax"}</dt><dd>+86-575-82738399</dd></div><div><dt>${zh?"地址":"Address"}</dt><dd>${zh?"浙江省绍兴市上虞区杭州湾上虞经济技术开发区纬九路3号":"No. 3 Wei 9 Road, Hangzhou Bay Shangyu Economic & Technological Development Area, Shangyu, Shaoxing, Zhejiang"}</dd></div></dl></div></section><section class="contact-routes"><div class="wrap"><a href="#products"><span>01</span><b>${zh?"产品与销售":"Products & sales"}</b><i>↗</i></a><a href="#quality/collaboration"><span>02</span><b>${zh?"研发合作":"Research collaboration"}</b><i>↗</i></a><a href="#careers/openings"><span>03</span><b>${zh?"人才招聘":"Careers"}</b><i>↗</i></a><a href="#products/adverse"><span>04</span><b>${zh?"质量与不良反应":"Quality & adverse events"}</b><i>↗</i></a></div></section>`; }
function enquiryPage(){ return `${sectionHead(zh?"合作咨询":"Cooperation enquiry","Contact & cooperation",zh?"用于本地演示的普通联系表单；当前不发送、不保存信息。":"A local demonstration general-enquiry form; it does not send or store information.")}<section class="section form-page"><div class="wrap"><form class="demo-form enquiry-form"><label>${zh?"称谓":"Name"}<input></label><label>${zh?"公司名称":"Company"}<input></label><label>${zh?"所在地区":"Region"}<input></label><label>${zh?"联系方式":"Contact details"}<input></label><label>${zh?"咨询类型":"Enquiry type"}<select><option>${zh?"产品咨询":"Product enquiry"}</option><option>${zh?"制造与合作":"Manufacturing & cooperation"}</option><option>${zh?"研发合作":"Research collaboration"}</option></select></label><label>${zh?"留言内容":"Message"}<textarea rows="6"></textarea></label><p>${zh?"演示表单，暂不发送、不保存任何信息。":"Demo form only: no information is sent or stored."}</p><button type="button" disabled>${zh?"演示表单，暂不发送":"Demo form — not sent"}</button></form></div></section>`; }
function searchPage(){ return `${sectionHead(labels.search,"Search",zh?"搜索产品、页面、动态或公开信息。":"Search products, pages, updates or disclosures.")}<section class="section search-page"><div class="wrap"><label class="search-field"><span>${zh?"搜索内容":"Search"}</span><input id="site-search" type="search" autofocus placeholder="${zh?"输入关键词":"Enter a keyword"}"></label><div id="site-results" class="search-results"></div></div></section>`; }
function missing(){ return `${sectionHead("404","Kinglyuan Pharmaceutical",zh?"未找到所请求的页面。":"The requested page could not be found.")}<section class="section"><div class="wrap"><a class="button" href="#home">${labels.home}</a></div></section>`; }

function bindProducts(initialType){ const input=document.querySelector("#product-search"), count=document.querySelector("#product-count"), output=document.querySelector("#product-results"), controls=document.querySelector("#product-filters"); if(!count || !output || !controls) return; let type=initialType, query=""; const draw=()=>{ if(!document.body.contains(count) || !document.body.contains(output)) return; const shown=data.product.filter(p=> (type === "all" || typeOf(p)===type) && `${compactTitle(p.title)} ${PRODUCT_EN[p.id]||""} ${p.auditedText||""}`.toLowerCase().includes(query.toLowerCase())); count.textContent=zh?`显示 ${shown.length} / ${data.product.length} 项产品`:`Showing ${shown.length} of ${data.product.length} products`; output.innerHTML=shown.map(productCard).join("") || `<p>${zh?"未找到匹配产品。":"No matching products."}`; }; input?.addEventListener("input",e=>{query=e.target.value;draw();}); controls.addEventListener("click",e=>{const btn=e.target.closest("button[data-type]"); if(!btn)return; type=btn.dataset.type; controls.querySelectorAll("button").forEach(x=>x.classList.toggle("is-active",x===btn)); draw();}); draw(); }
function bindCounters(){ if(matchMedia("(prefers-reduced-motion: reduce)").matches) return; const zone=document.querySelector("[data-counter-zone]"); if(!zone)return; let done=false; const run=()=>{ if(done)return; done=true; zone.querySelectorAll(".metric").forEach(metric=>{const out=metric.querySelector("b"), target=Number(metric.dataset.value), prefix=metric.dataset.prefix||"", suffix=metric.dataset.suffix||"", start=performance.now(), duration=980; const tick=(now)=>{const progress=Math.min(1,(now-start)/duration), eased=1-Math.pow(1-progress,3), n=Math.round(target*eased); out.innerHTML=`${prefix?`<small>${prefix}</small>`:""}<em>${n}</em>${suffix?`<i>${suffix}</i>`:""}`; if(progress<1)requestAnimationFrame(tick);}; requestAnimationFrame(tick);});}; new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))run();},{threshold:.45}).observe(zone); }
function bindGallery(){ const dialog=document.querySelector(".gallery-dialog"); if(!dialog)return; let index=0; const renderImage=()=>{const id=galleryOrder[index], img=dialog.querySelector("img");img.src=A(`gallery/qy${id}.jpg`);img.alt=zh?`金立源公开企业展示图片 ${id}`:`Official Kinglyuan company-exhibition image ${id}`;dialog.querySelector("figcaption").textContent=zh?`企业展示 ${String(id).padStart(2,"0")} / ${galleryOrder.length}`:`Company exhibition ${String(id).padStart(2,"0")} / ${galleryOrder.length}`;}; document.querySelectorAll("[data-gallery]").forEach(btn=>btn.addEventListener("click",()=>{index=galleryOrder.indexOf(Number(btn.dataset.gallery));renderImage();dialog.showModal();})); document.querySelector(".gallery-expand")?.addEventListener("click",e=>{const rest=document.querySelector(".gallery-rest"), isHidden=rest.hidden;rest.hidden=!isHidden;e.currentTarget.setAttribute("aria-expanded",String(isHidden));e.currentTarget.textContent=isHidden?(zh?"收起完整图库":"Collapse full archive"):(zh?"查看全部 15 张图片":"View all 15 images");}); dialog.querySelector(".gallery-prev")?.addEventListener("click",()=>{index=(index-1+galleryOrder.length)%galleryOrder.length;renderImage();});dialog.querySelector(".gallery-next")?.addEventListener("click",()=>{index=(index+1)%galleryOrder.length;renderImage();}); }
function bindCredentials(){ const dialog=document.querySelector(".source-dialog"); if(!dialog)return; const records=zh?[["互联网药品信息服务资格备案","浙网药信备字(2026)00004号","官网页脚公开信息"],["绍兴市专利示范企业","公开科研成果页面记录","官网科研成果页"],["国家高新技术企业","公开科研成果页面记录","官网科研成果页"]]:[["Internet Pharmaceutical Information Service Filing","Zhe Internet Drug Information Filing No. (2026)00004","Official website footer"],["Shaoxing Patent Demonstration Enterprise","Recorded on the public research-results page","Official research-results page"],["National High-tech Enterprise","Recorded on the public research-results page","Official research-results page"]]; document.querySelectorAll("[data-credential]").forEach(btn=>btn.addEventListener("click",()=>{const x=records[Number(btn.dataset.credential)];dialog.querySelector("h2").textContent=x[0];dialog.querySelector(".source-meta").textContent=x[1];dialog.querySelector(".source-origin").textContent=`${zh?"来源：":"Source: "}${x[2]}`;dialog.showModal();})); }
function bindDialogs(){ document.querySelectorAll(".dialog-close").forEach(button=>button.addEventListener("click",()=>button.closest("dialog")?.close())); }
function bindSearch(){ const field=document.querySelector("#site-search"), out=document.querySelector("#site-results"); const pages=[["about",labels.about],["products",labels.products],["quality",labels.quality],["news",labels.news],["responsibility",labels.responsibility],["disclosure",labels.disclosure],["careers",labels.careers],["contact",labels.contact]]; const draw=()=>{const q=field.value.trim().toLowerCase();const result=[...data.product.map(p=>({to:`products/${p.id}`,type:labels.products,title:productName(p)})),...data.news.map(n=>({to:`news/${n.id}`,type:labels.news,title:n.title})),...pages.map(([to,title])=>({to,type:zh?"页面":"Page",title}))].filter(x=>!q||`${x.title} ${x.type}`.toLowerCase().includes(q));out.innerHTML=result.map(x=>`<a href="#${x.to}"><small>${x.type}</small><strong>${x.title}</strong><i>↗</i></a>`).join("") || `<p>${zh?"未找到匹配内容。":"No matching content."}</p>`;};field.addEventListener("input",draw);draw(); }
function bindReveal(){ if(matchMedia("(prefers-reduced-motion: reduce)").matches)return; const nodes=[...document.querySelectorAll(".section, .quality-overview, .responsibility-landing, .culture-lead")]; const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in-view");observer.unobserve(e.target)}}),{threshold:.1});nodes.forEach(n=>observer.observe(n)); }
function render(){ shell(); const [section,sub]=route().split("/"); const main=document.querySelector("#main"); main.innerHTML=section==="home"?home():section==="about"?about(sub):section==="products"?(sub && /^\d+$/.test(sub)?productDetail(sub):products(sub)):section==="quality"?quality(sub):section==="news"?(sub && /^\d+$/.test(sub)?newsDetail(sub):news(sub)):section==="responsibility"?responsibility(sub):section==="disclosure"?disclosure():section==="careers"?careers(sub):section==="contact"?contact(sub):section==="search"?searchPage():missing(); if(section==="products" && !(sub&&/^\d+$/.test(sub)))bindProducts(["formulation","api","intermediate","other"].includes(sub)?sub:"all"); if(section==="home")bindCounters(); if(section==="about"){bindGallery();bindCredentials();} if(section==="search")bindSearch();bindDialogs();bindReveal(); window.scrollTo({top:0,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}); document.querySelector("#main").focus({preventScroll:true}); }
addEventListener("hashchange",render); render();
